#!/bin/sh

#force exit for now
#exit 0

HOOK_DIR="$(git rev-parse --show-toplevel)/.git/hooks"
LOG_FILE="$HOOK_DIR/pre-commit.log"

"$HOOK_DIR/pre-commit-client.exe" > "$LOG_FILE" 2>&1
EXIT_CODE=$?
#echo "Exit code from pre-commit-client.exe: $EXIT_CODE"

if [ $EXIT_CODE -ne 0 ]; then
  echo "Commit blocked: Pre-commit check/s failed."
  cat "$LOG_FILE"
  exit 1 
fi

rm -f "$LOG_FILE"
exit 0